// <auto-generated />
using System;
using FamilyHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyHub.Api.Data.Migrations
{
    [DbContext(typeof(FamilyHubDbContext))]
    [Migration("20260824093904_AddFirstAidTracker")]
    partial class AddFirstAidTracker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyHub.Api.Chores.Chore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedFamilyMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedFamilyMemberId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("FamilyHub.Api.Chores.ChoreOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.ToTable("ChoreOccurrences");
                });

            modelBuilder.Entity("FamilyHub.Api.Expiry.ExpiryFacet", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.ToTable("ExpiryFacets");
                });

            modelBuilder.Entity("FamilyHub.Api.FirstAid.StockFacet", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.ToTable("StockFacets");
                });

            modelBuilder.Entity("FamilyHub.Api.Households.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleSubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("FamilyHub.Api.Households.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Households");
                });

            modelBuilder.Entity("FamilyHub.Api.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FamilyHub.Api.Warranties.WarrantyFacet", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentExternalId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PurchasedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("WarrantyExpiresOn")
                        .HasColumnType("date");

                    b.HasKey("ItemId");

                    b.ToTable("WarrantyFacets");
                });

            modelBuilder.Entity("FamilyHub.Api.Chores.Chore", b =>
                {
                    b.HasOne("FamilyHub.Api.Households.FamilyMember", null)
                        .WithMany()
                        .HasForeignKey("AssignedFamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyHub.Api.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyHub.Api.Chores.ChoreOccurrence", b =>
                {
                    b.HasOne("FamilyHub.Api.Chores.Chore", null)
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyHub.Api.Expiry.ExpiryFacet", b =>
                {
                    b.HasOne("FamilyHub.Api.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("FamilyHub.Api.Expiry.ExpiryFacet", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyHub.Api.FirstAid.StockFacet", b =>
                {
                    b.HasOne("FamilyHub.Api.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("FamilyHub.Api.FirstAid.StockFacet", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyHub.Api.Households.FamilyMember", b =>
                {
                    b.HasOne("FamilyHub.Api.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyHub.Api.Items.Item", b =>
                {
                    b.HasOne("FamilyHub.Api.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyHub.Api.Warranties.WarrantyFacet", b =>
                {
                    b.HasOne("FamilyHub.Api.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("FamilyHub.Api.Warranties.WarrantyFacet", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
